// <auto-generated />
namespace DQueensFashion.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ReadAddedToDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReadAddedToDb));
        
        string IMigrationMetadata.Id
        {
            get { return "202007121700242_ReadAddedToDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
