// <auto-generated />
namespace DQueensFashion.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class userIdChangedtoString : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userIdChangedtoString));
        
        string IMigrationMetadata.Id
        {
            get { return "202005240810027_userIdChangedtoString"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
