// <auto-generated />
namespace DQueensFashion.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ReadAddedToDb2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReadAddedToDb2));
        
        string IMigrationMetadata.Id
        {
            get { return "202007121707417_ReadAddedToDb2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
